name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"      # Har roz raat ko update hota rahe
  workflow_dispatch:         # Manually trigger karne ke liye

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        id: snake
        with:
          github_user_name: ankitkr52
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
